---
title: "Data Science Recipes"
subtitle: "Examples in Binary Classification"
author: "Mark Newman"
lof: true
lot: true
paged-footnotes: true
links-to-footnotes: true
toc-title: Table of Contents
output:
  pagedown::html_paged: 
    toc: true
    number_sections: yes
    pandoc_args: --mathjax
    self_contained: yes
editor_options: 
  chunk_output_type: console
bibliography: [_references.bib, _packages.bib, _datasets.bib]
link-citations: yes
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/ieee-with-url.csl
url: 'https\://github.com/markanewman/DataScienceRecipes'
github-repo: markanewman/DataScienceRecipes
---

```{r echo = F, message = F}
here::i_am('index.rmd')
```

```{r child = 'book/100 introduction.rmd'}
```

```{r child = 'book/200 understanding.rmd'}
```

```{r child = 'book/300 figures.rmd'}
```

```{r child = 'book/400 tables.rmd'}
```

```{r child = 'book/500 modeling.rmd'}
```

```{r child = 'book/600 ml.rmd'}
```

```{r child = 'book/700 examples.rmd'}
```

# References {-}

---
nocite: | 
  @github, @rlanguage, @rstudio
---
